# Generated by Django 5.1 on 2024-09-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('slug', models.CharField(max_length=100, verbose_name='Slug')),
                ('text', models.TextField(verbose_name='Cодержимое')),
                ('image', models.ImageField(upload_to='blog_image', verbose_name='Превью')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Признак публикации')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'пост для блога',
                'verbose_name_plural': 'посты для блога',
            },
        ),
    ]
