# Generated by Django 5.1 on 2024-08-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_storecontacts_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия пользователя')),
                ('email', models.CharField(max_length=100, verbose_name='Электронная почта пользователя')),
            ],
            options={
                'verbose_name': 'контакт пользователя',
                'verbose_name_plural': 'контакты пользователя',
            },
        ),
    ]
