# Generated by Django 4.2 on 2024-10-04 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_published', 'Can publish product'), ('edit_description', 'Can edit description'), ('change_category_product', 'Can change category of product')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
